
export const projects = [
        {id:1,name:"HDR House",category:"residential",
        heroimage: "/images/projects/HDR-hero.webp",
        mainimage: "/images/projects/HDR-House-main.webp",
        images:[
            "/images/projects/HDR-1.webp",
            "/images/projects/HDR-2.webp",
            "/images/projects/HDR-3.webp",
            "/images/projects/HDR-4.webp",
            "/images/projects/HDR-5.webp",
            "/images/projects/HDR-6.webp",
            "/images/projects/HDR-7.webp",
            "/images/projects/HDR-8.webp",
            "/images/projects/HDR-9.webp",
            "/images/projects/HDR-10.webp",
            "/images/projects/HDR-11.webp",
        ],
        year: "2023",
        location: "Semarang, Central Java",
        country: "Indonesia",
        type: "Residential",
        status: "Built",
        landsize: "600 sqm",
        stories: [
            "The HDR House, situated atop a Semarang hill, stands out for its dual front and back views, a rarity in urban residences. This innovative design not only redefines city living but also addresses the specific needs and desires of the client.",
            "The client, an introvert with a paradoxical desire for openness to greenery and nature, inspired our unique approach. An enclosed wall at the front offers privacy, while the house's side opens up, seamlessly connecting with nature. This approach caters to the client's need for solitude amidst the scenic beauty.",
            "Tailored as a retirement home, the HDR House doesn't compromise on elegance, requiring fewer rooms. The open-plan design, transparent from the front to the backyard, fulfills the client's wish for a spacious yet private sanctuary. A colossal protective wall shields the residence from the outside world, ensuring a secure and serene retirement haven.",
            "This innovative design not only redefines city living but also addresses the specific needs and desires of the client. The HDR House remains a testament to harmonizing nature, privacy, and panoramic city views, creating an unparalleled residential masterpiece.",
        ]
    },
        {id:2,name:"LA House",category:"residential",
        heroimage: "/images/projects/LA-hero.webp",
        mainimage: "/images/projects/LA-House-main.webp",
        images:[
            "/images/projects/LA-1.webp",
            "/images/projects/LA-2.webp",
            "/images/projects/LA-3.webp",
            "/images/projects/LA-4.webp",
        ],
        year: "2022",
        location: "West Jakarta, Greater Jakarta",
        country: "Indonesia",
        type: "Residential",
        status: "Built",
        landsize: "300 sqm",
        stories: [
            "LA House, a marvel in efficient design, maximizes functionality on limited land. The owner's passion for outdoor gatherings led us to craft multiple-level gardens, seamlessly integrated with each room. Accessibility and easy maintenance were paramount, prompting innovative solutions like a spacious ceiling room for repairs and strategically thinned beams using sleek wood materials.",
            "LA House is a testament to innovative design, harmonizing functionality with a limited footprint. Each room seamlessly connects to multiple-level gardens, creating a dynamic space for outdoor activities and garden parties. The owner's vision of an easily maintainable home is realized through thoughtful features, including a spacious ceiling room for repairs and streamlined, sharpened wood beams.",
            "In the heart of LA House lies a harmonious blend of space and nature. Despite limited land, the design accommodates numerous functions while prioritizing the owner's love for outdoor activities. Multiple-level gardens, accessible from every room, create a vibrant connection with nature, turning the entire residence into a dynamic, inviting space.",
            "Efficiency meets elegance in LA House's design, a response to the challenge of limited land space. We've seamlessly integrated outdoor spaces into every room, fulfilling the owner's desire for garden parties and easy access to nature. The building's innovative features, such as a spacious ceiling room and strategically thinned wood beams, ensure hassle-free maintenance.",
        ]
    },
        {id:3,name:"Kiyana Hotel",category:"hospitality",
        heroimage: "/images/projects/Kiyana-hero.webp",
        mainimage: "/images/projects/Kiyana-Hotel-main.webp",
        images:[
            "/images/projects/Kiyana-1.webp",
            "/images/projects/Kiyana-2.webp",
            "/images/projects/Kiyana-3.webp",
        ],
        year: "2022",
        location: "Batang, Central Java",
        country: "Indonesia",
        type: "Hospitality",
        status: "Built",
        landsize: "1500 sqm",
        stories: [
            "Introducing the Kiyana Hotel, an elegant business haven nestled in the burgeoning industrial landscape of Central Java. Formerly an abandoned guest house, this renovation project transforms it into a modern marvel dominated by sleek black steel and expansive clear glass, exuding a sophisticated and contemporary vibe.",
            "The Kiyana Hotel welcomes guests with a first impression of timeless elegance and modernity. The commanding presence of black steel, complemented by vast clear glass, creates an atmosphere of sophistication and exclusivity, setting the tone for a refined hospitality experience in the heart of Central Java's industrial growth.",
            "A carefully curated play of lighting adds a touch of warmth and comfort to the Kiyana Hotel's chic ambiance. Thoughtfully designed illumination enhances the guest experience, creating an inviting atmosphere that balances the sleek modernity of black steel and glass with a sense of welcome and relaxation.",
            "In a subtle juxtaposition, the Kiyana Hotel achieves a soft aesthetic through the strategic use of stone and wood elements. These materials counterbalance the intensity of the black steel, infusing the hotel with a harmonious blend of textures that invite guests to experience a luxurious and inviting retreat in the midst of Central Java's industrial dynamism.",
        ]
    },
        {id:4,name:"GL House",category:"residential",
        heroimage: "/images/projects/GL-hero.webp",
        mainimage: "/images/projects/GL-House-main.webp",
        images:[
            "/images/projects/GL-1.webp",
            "/images/projects/GL-2.webp",
            "/images/projects/GL-3.webp",
            "/images/projects/GL-4.webp",
            "/images/projects/GL-5.webp",
            "/images/projects/GL-6.webp",
            "/images/projects/GL-7.webp",
            "/images/projects/GL-8.webp",
        ],
        year: "2023",
        location: "BSD, Banten",
        country: "Indonesia",
        type: "Residential",
        status: "Built",
        landsize: "400 sqm",
        stories: [
            "Nestled in a cozy corner of the neighborhood, GL House is a tropical haven designed to radiate warmth and homeliness. Embracing the client's love for a tropical ambiance, we meticulously integrated natural materials like wood and stone, creating a seamless blend with the surroundings.",
            "Strategically situated beside a communal park, GL House capitalizes on its location with expansive openings. These openings serve as visual gateways, allowing the vibrant greenery from the park to seamlessly penetrate the interiors. The result is a symbiotic relationship between the residence and its natural surroundings, fostering a tranquil and refreshing atmosphere.",
            "GL House is not merely a structure; it's a harmonious embodiment of natural elements and contemporary living. The strategic use of wood and stone surfaces, coupled with thoughtful design, transforms the home into a serene retreat that effortlessly connects with the tropical beauty of its environment.",
            "In every detail of GL House, the integration of natural elements takes center stage. From the choice of materials to the placement within the neighborhood, the residence encapsulates the essence of a tropical paradise. GL House stands as a testament to the seamless fusion of modern comfort and the timeless allure of nature.",
        ]
    },
        {id:5,name:"Hashbay Cafe",category:"commercial",
        heroimage: "/images/projects/Hashbay-hero.webp",
        mainimage: "/images/projects/Hashbay-main.webp",
        images:[
            "/images/projects/Hashbay-1.webp",
            "/images/projects/Hashbay-2.webp",
            "/images/projects/Hashbay-3.webp",
            "/images/projects/Hashbay-4.webp",
            "/images/projects/Hashbay-5.webp",
            "/images/projects/Hashbay-6.webp",
            "/images/projects/Hashbay-7.webp",
            "/images/projects/Hashbay-8.webp",
            "/images/projects/Hashbay-9.webp",
            "/images/projects/Hashbay-10.webp",
            "/images/projects/Hashbay-11.webp",
            "/images/projects/Hashbay-12.webp",
            "/images/projects/Hashbay-13.webp",
        ],
        year: "2023",
        location: "Tegal, Central Java",
        country: "Indonesia",
        type: "Commercial",
        status: "Built",
        landsize: "180 sqm",
        stories: [
            "Introducing Hashbay, the town's inaugural fine-dining-concept cafe, setting a new standard for upscale culinary experiences. Step into tranquility with muted dark hues, diffused lighting, calming sounds, and subtle scents—transforming the traditional steakhouse vibe into a serene haven, where culinary excellence meets a refined, subdued ambiance.",
            "Hashbay, the avant-garde culinary destination, redefines the steakhouse experience. Embracing muted dark tones, diffused lighting, calming acoustics, and subtle scents, it crafts an atmosphere that transcends the conventional. This unique fusion of upscale dining and serene ambience promises patrons an extraordinary culinary journey within the town's first of its kind.",
            "Step into Hashbay, a groundbreaking fine-dining-concept cafe, where every detail is meticulously curated to transcend the ordinary. With its muted dark color palette, diffused lighting, calming sounds, and subtle scents, it introduces a serene ambiance that revolutionizes the traditional steakhouse, creating an unmatched culinary sanctuary.",
            "Hashbay stands as the epitome of sophistication, introducing a refined steakhouse experience to town. Its serene ambiance, marked by muted dark tones, diffused lighting, calming acoustics, and subtle scents, elevates the culinary journey. A departure from the rustic, Hashbay redefines fine dining with an atmosphere of elegance and tranquility.",
        ]
    },
        {id:6,name:"GIS Kindergarten",category:"commercial",
        heroimage: "/images/projects/GIS-hero.webp",
        mainimage: "/images/projects/GIS-Kindergarten-main.webp",
        images:[
            "/images/projects/GIS-1.webp",
            "/images/projects/GIS-2.webp",
            "/images/projects/GIS-3.webp",
            "/images/projects/GIS-4.webp",
        ],
        year: "2023",
        location: "Tegal, Central Java",
        country: "Indonesia",
        type: "Education",
        status: "Under Construction",
        landsize: "800 sqm",
        stories: [
            "Introducing GIS Kindergarten, a vibrant icon of early education designed to captivate toddlers. In stark contrast to the serious and formal existing middle and high school buildings, our design radiates a playful atmosphere, creating lasting cheerful memories for the children.",
            "Strategically divided into two main buildings on the long, narrow site, GIS Kindergarten minimizes walking distances for the little ones. At the heart of the campus, a whimsical oasis features slides and playgrounds, transforming the surroundings into a joyful haven where children's imaginations can flourish.",
            "GIS Kindergarten stands as a testament to architecture aligned with the enchanting world of children. Its lively and engaging design fosters an environment that seamlessly integrates with the innocence and joy of early learning, making every day an adventure for the young minds within its walls.",
        ]
    },
        {id:7,name:"ID House",category:"residential",
        heroimage: "/images/projects/ID-hero.webp",
        mainimage: "/images/projects/ID-House-main.webp",
        images:[
            "/images/projects/ID-1.webp",
            "/images/projects/ID-2.webp",
            "/images/projects/ID-3.webp",
            "/images/projects/ID-4.webp",
        ],
        year: "2023",
        location: "BSD, Banten",
        country: "Indonesia",
        type: "Residential",
        status: "Built",
        landsize: "250 sqm",
        stories: [
            "Embodying the essence of tropical living, the ID House is a timeless masterpiece designed for a mature and settled family. The architecture seamlessly aligns with the owner's identity, reflecting a sense of enduring elegance that transcends trends and fads.",
            "In a captivating twist, the roof becomes a focal point as we peel it back, revealing an exclusive gym room with breathtaking views. This unexpected element adds a dynamic layer to the design, blending practicality with aesthetic allure.",
            "Nature serves as both shield and adornment in the ID House, where lush greenery acts as a barrier, creating a serene oasis within and enhancing the exterior. The strategic use of plants not only ensures privacy but also fosters a harmonious connection between the interior and the natural surroundings.",
            "ID House, with its matured and thoughtful design, redefines the concept of a family home. A synthesis of timeless aesthetics, functional innovation, and a flourishing green environment, it stands as a testament to the artistry of architecture in creating living spaces that resonate with the occupants' identity and aspirations.",
        ]
    },
        {id:8,name:"Headquarter PHG",category:"commercial",
        heroimage: "/images/projects/PHG-hero.webp",
        mainimage: "/images/projects/PHG-main.webp",
        images:[
            "/images/projects/PHG-1.webp",
            "/images/projects/PHG-2.webp",
            "/images/projects/PHG-3.webp",
            "/images/projects/PHG-4.webp",
        ],
        year: "2022",
        location: "Pekalongan, Central Java",
        country: "Indonesia",
        type: "Commercial",
        status: "Completed",
        landsize: "1000 sqm",
        stories: [
            "Introducing Headquarter PHG, a cutting-edge architectural marvel designed to embody the company's enduring strength and transparency. Crafted with raw concrete and steel, this structure stands as a symbol of unwavering resilience and honesty, mirroring the company's commitment to authenticity and longevity.",
            "Less adorned, more genuine  Headquarter PHG's minimalist aesthetic reflects the company's straightforward approach and sincerity towards its customers. The intentional absence of excessive ornamentation underscores the core values of transparency and trust, establishing a visual language that resonates with the company's ethos.",
            "In its contemporary design, Headquarter PHG echoes the progressive spirit of the company. This architectural masterpiece is more than just a building; it's a visual representation of the company's commitment to innovation and advancement. The sleek lines and modern elements convey a sense of forward-thinking that defines the character and ethos of the organization.",
            "More than bricks and mortar, Headquarter PHG is a semiotic embodiment of the company's work ethic. Every facet of its design speaks to the dedication, diligence, and dynamic nature of the organization, making it a distinctive landmark that reflects the progressive and enduring values of the company.",
        ]
    },
        {id:9,name:"AM Villa",category:"hospitality",
        heroimage: "/images/projects/AM-hero.webp",
        mainimage: "/images/projects/AM-main.webp",
        images:[
            "/images/projects/AM-1.webp",
            "/images/projects/AM-2.webp",
            "/images/projects/AM-3.webp",
            "/images/projects/AM-4.webp",
            "/images/projects/AM-5.webp",
            "/images/projects/AM-6.webp",
            "/images/projects/AM-7.webp",
        ],
        year: "2023",
        location: "Bandung, West Java",
        country: "Indonesia",
        type: "Hospitality",
        status: "On Going",
        landsize: "300 sqm",
        stories: [
            "Perched on a steep slope, AM Villa ingeniously adapts to its challenging terrain. The building masses intricately follow the natural contours, ensuring a one-of-a-kind villa that harmonizes with its surroundings. With three bedrooms and exclusive bookings for single groups, privacy takes center stage, accentuated by individual masses for each room.",
            "AM Villa's innovative design maximizes the unique topography, creating an exclusive retreat impossible to replicate. The villa, tailored for single-group occupancy in each rental cycle, promises an intimate escape. Multiple amphitheaters amplify the social spaces, fostering an atmosphere of shared enjoyment and camaraderie. This architectural gem seamlessly blends privacy, exclusivity, and communal experiences in a picturesque setting.",
            "Nestled on a challenging steep slope, AM Villa transforms adversity into architectural triumph. The building masses ingeniously mirror the natural contours, resulting in a villa that embraces its topographical uniqueness. Housing three bedrooms for exclusive single-group stays, the design accentuates privacy with individual masses for each room.",
            "AM Villa's innovative architecture capitalizes on the steep slope, creating a villa that defies replication. The three-bedroom retreat caters exclusively to single groups per rental cycle, ensuring an intimate and personalized experience. Multiple amphitheaters enhance social spaces, fostering a sense of shared enjoyment. The design seamlessly marries privacy, exclusivity, and communal interactions.",
            "Adapting gracefully to a challenging steep slope, AM Villa's design capitalizes on the site's natural contours. With three bedrooms available exclusively for single-group rentals, the villa promises a unique escape. Social spaces are enhanced by amphitheaters, creating an intimate and enjoyable atmosphere. Individual masses for rooms amplify the sense of privacy in this distinctive architectural gem.",
        ]
    },
        {id:10,name:"KH Headquarter",category:"commercial",
        heroimage: "/images/projects/KH-hero.webp",
        mainimage: "/images/projects/KH-main.webp",
        images:[
            "/images/projects/KH-1.webp",
            "/images/projects/KH-2.webp",
            "/images/projects/KH-3.webp",
        ],
        year: "2023",
        location: "Jakarta",
        country: "Indonesia",
        type: "Commercial",
        status: "Built",
        landsize: "800 sqm",
        stories: [
            "Introducing KH Headquarters, a transformative renovation project reshaping a conventional three-story shophouse into a dynamic corporate hub. The innovative design carves out a central void, fashioning an inviting inner courtyard that takes center stage. This reimagined space becomes the focal point, fostering collaboration and a vibrant work atmosphere.",
            "The existing structure's metamorphosis breathes new life into KH Headquarters, blending functionality with aesthetics. By hollowing out the floor slab, a harmonious balance emerges between the building's layers, culminating in a visually striking and purposeful inner courtyard. This design choice not only enhances the workspace but also reflects the company's commitment to transparency and innovation.",
            "In the heart of this revitalized headquarters lies the captivating inner courtyard. The once overlooked space now serves as a key feature, fostering a sense of connection and openness among employees. This thoughtful renovation elevates KH Headquarters beyond a mere office space, creating a dynamic environment that mirrors the company's progressive values and collaborative spirit.",
            "KH Headquarters' facade, predominantly adorned in pristine white, exudes an aura of honesty and sincerity. This intentional design choice aligns with the company's character, projecting transparency and trustworthiness to clients and visitors alike. The renovated shophouse transcends its traditional roots, becoming a symbol of innovation, collaboration, and corporate integrity.",
        ]
    },
        {id:11,name:"MOKSHA Garden",category:"commercial",
        heroimage: "/images/projects/Moksha-hero.webp",
        mainimage: "/images/projects/Moksha-Garden-main.webp",
        images:[
            "/images/projects/Moksha-1.webp",
            "/images/projects/Moksha-2.webp",
            "/images/projects/Moksha-3.webp",
            "/images/projects/Moksha-4.webp",
            "/images/projects/Moksha-5.webp",
            "/images/projects/Moksha-6.webp",
        ],
        year: "2022",
        location: "Ungaran, Central Java",
        country: "Indonesia",
        type: "Commercial",
        status: "Proposal",
        landsize: "49,000 sqm",
        stories: [
            "Introducing MOKSHA Garden, an architectural marvel nestled in the midst of a lush green forest, seamlessly blending with nature's tranquility. The site's serene and contemplative ambiance is accentuated by breathtaking views of a sacred mountain, creating a harmonious backdrop for this unique property complex.",
            "In crafting the design for MOKSHA Garden, our focus was to enhance rather than disturb the inherent serenity of the site. Despite the bustling functions planned, including a mall and crowd-attracting elements, our approach prioritizes a seamless integration with the natural surroundings. MOKSHA Garden becomes a sanctuary where modern amenities coexist in perfect harmony with the sacred beauty that envelops it.",
            "This visionary project ensures that the essence of the site remains undisturbed, offering visitors a one-of-a-kind experience where the vibrancy of a commercial hub meets the tranquility of a sacred haven. MOKSHA Garden stands as a testament to the delicate balance between architectural innovation and the preservation of nature's sanctity.",
        ]
    },
]